// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>
// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include "arduino_secrets.h"


const char DEVICE_LOGIN_NAME[]  = "71b9f870-8ecd-4da3-af83-cb43b2f7adf6";

// const char SSID[]               = SECRET_SSID;    // Network SSID (name)
// const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
// const char DEVICE_KEY[]  = SECRET_DEVICE_KEY; 

const char SSID[]       = "OnePlus115G";     // Your WiFi name
const char PASS[]       = "";       // Your WiFi password
const char DEVICE_KEY[] = "6LeH?4dLmZQ3@FWDJP7oi3rNf";   // Your IoT Cloud device key
// Secret device password


CloudHeartRate heartbeat;
CloudLocation location;
CloudPercentage oxygen;
CloudTemperature temperature;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(heartbeat, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(location, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(oxygen, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(temperature, READ, ON_CHANGE, NULL);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
